engines:
  checkstyle:
    enabled: true
    channel: beta
    checks:
      com.puppycrawl.tools.checkstyle.checks.javadoc.SummaryJavadocCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.naming.AbbreviationAsWordInNameCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.blocks.NeedBracesCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.sizes.LineLengthCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.imports.CustomImportOrderCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.imports.AvoidStarImportCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.blocks.RightCurlyCheck: #We got no right-curl. Always next line
        enabled: false

      # Reenable if "format" works...
      com.puppycrawl.tools.checkstyle.checks.naming.MethodNameCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.naming.ParameterNameCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.naming.TypeNameCheck:
        enabled: false
  fixme:
    enabled: true
  pmd:
    enabled: true
    channel: beta
ratings:
  paths:
  - "**.java"
exclude_paths: []