engines:
  checkstyle:
    enabled: true
    channel: beta
    checks:
      com.puppycrawl.tools.checkstyle.checks.javadoc.SummaryJavadocCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.naming.AbbreviationAsWordInNameCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.naming.ParameterNameCheck:
        enabled: true
        format: "^p[a-z][a-zA-Z0-9]*$"
  fixme:
    enabled: true
  pmd:
    enabled: true
    channel: beta
ratings:
  paths:
  - "**.java"
exclude_paths: []